export const endingFlashcards = [
  {
    id: 'air_100',
    image: require('../../../assets/images/air_100.png'),
    title: 'Sky Dominion',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'Excessive idealism detached humanity from reality. Societies crumbled as people pursued impossible dreams, neglecting basic needs.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/air_100.mp3'),
  },
  {
    id: 'air_0',
    image: require('../../../assets/images/air_100.png'),
    title: 'Grounded Eternity',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'Without vision, humanity became stagnant. No progress was made as fear of failure prevented any ambitious endeavors.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/air_100.mp3'),
  },
  {
    id: 'earth_100',
    image: require('../../../assets/images/earth_100.png'),
    title: 'Stone Age Redux',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'Total focus on stability led to rigidity. Innovation ceased, and societies collapsed under the weight of unchangeable tradition.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/air_100.mp3'),
  },
  {
    id: 'earth_0',
    image: require('../../../assets/images/earth_100.png'),
    title: 'Floating Foundations',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'Lack of grounding caused chaos. With no roots, communities drifted aimlessly, unable to build lasting systems or trust.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/air_100.mp3'),
  },
  {
    id: 'fire_100',
    image: require('../../../assets/images/fire_100.png'),
    title: 'Ashes of Glory',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'Unchecked ambition led to war and destruction. Great achievements came at the cost of widespread suffering and irreversible damage.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/fire_100.mp3'),
  },
  {
    id: 'fire_0',
    image: require('../../../assets/images/fire_100.png'),
    title: 'Frozen Hearts',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'With no drive, humanity grew cold. Life became mechanical, passionless, and devoid of creation or courage.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/fire_0.mp3'),
  },
  {
    id: 'water_100',
    image: require('../../../assets/images/water_100.png'),
    title: 'Drowned in Empathy',
    description: { yes: "Restart!", no: "Restart..." },
    description: 'Too much compassion led to indecision and collapse. Boundaries dissolved as emotions ruled over reason and structure.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/air_100.mp3'),
  },
  {
    id: 'water_0',
    image: require('../../../assets/images/water_100.png'),
    title: 'Desert of Connection',
    description: { yes: "Restart!", no: "Restart..." },
    question: 'Emotional neglect turned societies dry and isolating. Without empathy, relationships withered and collective strength faded.',
    color: { yes: 'white', no: 'black' },
    music: require('../../../assets/music/ending/air_100.mp3'),
  },  
];